locale: "ko-KR"
title: "opficdev"
title_separator: "-"
name: "opficdev"
description: "기록하는 iOS 개발자"
url: "https://opficdev.github.io"
baseurl: ""
repository: "opficdev/opficdev.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.28.1"
minimal_mistakes_skin: "default"

search: false
show_excerpts: false
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Asia/Seoul
words_per_minute: 200

logo:

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
